### ISSUE TITLE
Unresponsive input & crash

### ISSUE THREAD

**Issue by MrTanoshii** [MrTanoshii/PyWeek-33-Metro#130]
From a Discord server message
---

I have encountered a gameplay bug. When I am controlling the car, after a while, the car starts moving on its own and does not respond to my input. Occasionally I will see a popup at the lower left corner that is telling me to choose à,á,â,ä,æ,a,ã,å or ā. I am on a mac. This is with python 3.8.8. When I use python 3.9, I get this:

Traceback (most recent call last):
  File "v1.1 source/The Epic of Goat v1.1.0/main.py", line 47, in <module>
    main()
  File "v1.1 source/The Epic of Goat v1.1.0/main.py", line 24, in main
    window = arcade.Window(
TypeError: init() got an unexpected keyword argument 'style'

---

User tried to turn `FULLSCREEN_WINDOWED = False` in `const/window.py` but the error persisted.

**Comment by MrTanoshii** [comment]
## From pyweek feedback

The controls were buggy and delayed and not always working on my laptop (MacOS), but otherwise it would have been given "above average" for production. Was there a way you could have spiced up the storytelling in the intro? The goat theme was funny

**Comment by MrTanoshii** [comment]
## From PyWeek feedback

Cool! I really liked the graphics, they were super awesome: really cool concept with the man and his goat :) ... this should have been made for that pyweek where we almost voted in “goats goats goats!” as the theme! The sound of the magnum firing is extremely satisfying ... I had a few issues with the controls? The keys would keep sticking for me (both asdw and trigger on the mouse) which made the game a bit too hard to progress past the first couple of stages. Great work!

**Comment by MrTanoshii** [comment]
https://github.com/pyglet/pyglet/issues/171
